
on:
  push:
    tags:
      - 'v*'
name: front
jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: docker/build-push-action@v1
        with:
          registry: docker.pkg.github.com
          dockerfile: ./docker/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository:  2tons/front-end/web
          tag_with_ref: true
          tags: latest
    - uses: actions/checkout@master
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      with:
        args: set image deployment front front=docker.pkg.github.com/${{ github.repository }}/web:${RELEASE_VERSION}